### PR TITLE
SP2-159 SourceDataManager API

### PR DESCRIPTION
**Pull request by KonyakB**
- added api
- added summer_period.csv

to get summer_period.csv:
http://localhost:5165/api/TimeSeriesData?season=summer

to get winter_period.csv:
http://localhost:5165/api/TimeSeriesData?season=winter

### CODE REVIEW

**Comment by pkyeager** [comment]
image

**Comment by KonyakB** [comment]
thats weird bc it works for me

**Review by magwrap — CHANGES_REQUESTED** [review]
Getting DateTimeParse error 
```
System.TypeInitializationException: The type initializer for 'SourceDataManagerAPI.SourceDataManagerModel' threw an exception.
 ---> System.AggregateException: One or more errors occurred. (String '2/13/23 0:00' was not recognized as a valid DateTime.)
 ---> System.FormatException: String '2/13/23 0:00' was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(ReadOnlySpan`1 s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at System.Convert.ToDateTime(String value, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Heatington.Services.Serializers.CsvData.ConvertRecords[T]() in /home/janm23/Documents/University/semester_project/Heatington/Heatington/Services/Serializers/CsvSerializer.cs:line 94
   at Heatington.Controllers.CsvController.GetDataAsync() in /home/janm23/Documents/University/semester_project/Heatington/Heatington/Controllers/CsvController.cs:line 23
   at Heatington.SourceDataManager.SDM.FetchTimeSeriesDataAsync() in /home/janm23/Documents/University/semester_project/Heatington/Heatington/SourceDataManager/SDM.cs:line 29
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at SourceDataManagerAPI.SourceDataManagerModel..cctor() in /home/janm23/Documents/University/semester_project/Heatington/Heatington.SDM.Microservice/SourceDataManagerModel.cs:line 30
   --- End of inner exception stack trace ---
   at SourceDataManagerAPI.Controllers.TimeSeriesDataController.Get(String season) in /home/janm23/Documents/University/semester_project/Heatington/Heatington.SDM.Microservice/TimeSeriesDataController.cs:line 19
   at lambda_method2(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

HEADERS
=======
Accept: */*
Host: localhost:5165
User-Agent: insomnia/9.2.0
```

**Comment by magwrap** [comment]
Also, could you rename the directory and `.csproj` file to Heatington.Microservice.SDM, so it's the same as the rest?

**Comment by KonyakB** [comment]
oh ok when i checked the am had it in a way i have it currently but sure

**Comment by KonyakB** [comment]
> Getting DateTimeParse error
i have no idea whats wrong with this, this error message is from where?

**Comment by KonyakB** [comment]
might've found the problem but im not sure, the summer period i made yesterday had a different dat format compared to the one we have in winter period (i had hh:mm instead of h:mm)

**Review by magwrap — APPROVED** [review]
works like a charm, gonna merge bcs need to work on opt api

**Pull request merged**
