### PR TITLE
SP-90-Create-SourceDataManager-Class

### PR DESCRIPTION
**Pull request by pkyeager**
Dear Team,

Daniel (OrangeBlaze) and I have worked on the SDM module. You can test the functionality by running the application and checking the console.

The SDM is not fully finished yet because we still have to write unit testing classes for the relevant components. However, we aim to provide the current SDM to the OPT team, for example, to test their own implementations.

The codebase should be adequately documented, except for CsvController.cs, which will be updated in the next few days. A full documentation is not required at the moment due to our implementation of SOLID Principles and OOP, making the code relatively easy to understand and implement.

If you have further questions or suggestions, please feel free to give us feedback.

Thank you for your attention and collaboration!

Daniel (OrangeBlaze) and Mark (pkayeager)

### CODE REVIEW

**Comment by frske** [comment]
A few questions: 
- I see that the MVC architecture was implemented. How should other modules be organized based on this architecture? 
- In DataPoint.cs `this.` is used which goes against our coding style 
- No class has a .ToString override which would be useful 
- Program.cs was pushed but that should always be blank, maybe we should add it to the .gitignore like Jan suggested 
- Otherwise very very clean code. Great work!

**Comment by pkyeager** [comment]
Thank you @frske for the review. 

- I see that the MVC architecture was implemented. How should other modules be organized based on this architecture?
- > **I think, this is not a fully implemented MVC, because we don't have Views. It's quite close, but it may be repository or** data-handler pattern. I didn't follow a specific, I did that by accident.
- In DataPoint.cs this. is used which goes against our coding style
- > **Roger, I did that because of the readability because startTime and StartTime can be quite confusing** 
- No class has a .ToString override which would be useful
-> **Will take a look at that**
- Program.cs was pushed but that should always be blank, maybe we should add it to the .gitignore like Jan suggested
- > **Oh yes, that's true, I wrote todo in the program class**
- Otherwise very very clean code. Great work!
- > **Thank you, I appreciate that!**

**Comment by frske** [comment]
Another thing I just noticed, once the sourceDataManager loads the time series, there's no way to actually get the time series data from other modules

**Comment by pkyeager** [comment]
@frske You meant the access to the TimeSeriesData from the other modules for example AM or OPT?

**Comment by pkyeager** [comment]
> @frske You meant the access to the TimeSeriesData from the other modules for example AM or OPT?

should be accessible now.

**Comment by magwrap** [comment]
_Conflicts resolved !_

I don't know why but every change let's say when the name of the namespace was changed(I think Mark did it through vs code in browser) was seen as a conflict. 

Maybe it's better to do the changes from the code editor level?

Anyways, here's what I've done
- sqashed a few commits mostly for practice, those were anyway commits like formatted this and that, the descriptions ale still there but as in name "sqashed" into one commit
- added SP2-90 to some commits that didn't include that (I think those were also the browser vscode commits)
- resolved conflicts --> **Check if everything is correct**

ps. interactive rebase is op `git rebase -i origin/dev` (from the SP2-90 branch)

**Review by magwrap — CHANGES_REQUESTED** [review]
I think most of it is good. _I won't merge it yet._

to fix:
- there are some warnings during a dotnet build
- shouldn't CsvDataSource also implement IReadWriteController Interface, for better readability? It's in SP2-85 pull request.
- in try-catch blocks rethrow the exceptions ex:
```csharp
catch(Exception ex)
{
    Console.Writeline(ex);
    throw;
}
```

questions:
- @0rangeBlaze are all those if-else statement  in CsvController necessary? can't we do it in a different way? It just looks ugly, but I know that most of the time working code = ugly code
- @pkyeager what is the formatting issue in DataPoint?

**Comment by pkyeager** [comment]
@magwrap I've rebased your SP-85 into mine and experimented with the implementation of IReadWriteController. 

If you want me to use your IReadWriteController.cs and if it should fully replace GetData() and SaveData(), you have to rewrite the signatures. 

I am not sure, if you could have generics, which would be flexible enough. CsvDataSource was built for SDM only. 

I could use your Read and WriteData also as a wrapper, but then we have 1 more layer for same purpose?

Warning are from FrancescoDummyClasses(which will get replaced) and CsvController.cs(which for sure will be updated).

I will now take a look at formatting issue and write the re-throwing statement.

**Comment by pkyeager** [comment]
@magwrap What do you think about closing this PR and move create a new one for SP-90 merge to SP-11? I tried to edit it here, but it didn't work out, any suggestion?

**Comment by frske** [comment]
would it be possible to change the name of the namespace OR the class to only be SDM as now to instantiate it it is required to call as `SourceDataManager.SourceDataManager sourceDataManager = new()`

**Comment by frske** [comment]
Another thing that I just noticed, is that to instantiate the sourceDataManager I need to provide it with a path. I think it should not be the responsibility of other modules to specify a path in which the assets are held. But I might be wrong. 
@pkyeager what do you think

**Comment by magwrap** [comment]
> @magwrap I've rebased your SP-85 into mine and experimented with the implementation of IReadWriteController.
> 
> If you want me to use your IReadWriteController.cs and if it should fully replace GetData() and SaveData(), you have to rewrite the signatures.
> 
> I am not sure, if you could have generics, which would be flexible enough. CsvDataSource was built for SDM only.
> 
> I could use your Read and WriteData also as a wrapper, but then we have 1 more layer for same purpose?
> 
> Warning are from FrancescoDummyClasses(which will get replaced) and CsvController.cs(which for sure will be updated).
> 
> I will now take a look at formatting issue and write the re-throwing statement.

I don't think I fully understand what do you mean by rewriting the signatures?

Switching to generics is a good idea I'll do that. 

All looks good, check Francesco's comments, and if you're not planning to use stuff form SP2-85 concider reverting the rebase from this branch so not to make a mess with unnecessary stuff. 

I think it's better to stay on this PR because we can see the history of changes, and we're almost done and ready to merge.

**Comment by pkyeager** [comment]
> would it be possible to change the name of the namespace OR the class to only be SDM as now to instantiate it it is required to call as `SourceDataManager.SourceDataManager sourceDataManager = new()`

We wrote about this a couple days ago about your OPT, this is because the team decided to go with individual folder for each module and due to that, when the class and namespace share the same name, .NET requires you to write it in this manner.

**Comment by pkyeager** [comment]
> > @magwrap I've rebased your SP-85 into mine and experimented with the implementation of IReadWriteController.
> > If you want me to use your IReadWriteController.cs and if it should fully replace GetData() and SaveData(), you have to rewrite the signatures.
> > I am not sure, if you could have generics, which would be flexible enough. CsvDataSource was built for SDM only.
> > I could use your Read and WriteData also as a wrapper, but then we have 1 more layer for same purpose?
> > Warning are from FrancescoDummyClasses(which will get replaced) and CsvController.cs(which for sure will be updated).
> > I will now take a look at formatting issue and write the re-throwing statement.
> 
> I don't think I fully understand what do you mean by rewriting the signatures?
Your current Interface has a signature of ReadData() return string?, which is fine, because another classes could have their own internal implementation in convert string into whatever it needs. By rewriting signature I meant maybe changing it to generics. 
> Switching to generics is a good idea I'll do that.
> All looks good, check Francesco's comments, and if you're not planning to use stuff form SP2-85 concider reverting the rebase from this branch so not to make a mess with unnecessary stuff.
I use your utility tho.
> I think it's better to stay on this PR because we can see the history of changes, and we're almost done and ready to merge.
Alright sir

**Comment by magwrap** [comment]
Again rebased branch onto dev, so I'ts up to date. Check if everything is correct and I think we can finally merge.

**Comment by frske** [comment]
Could we add the inheritance from IClonable before we merge?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by magwrap** [comment]
> Could we add the inheritance from IClonable before we merge? Sent from Outlook for Android<https://aka.ms/AAb9ysg>
> […](#)
Could you res-send the link? It doesn't work in my browser

**Comment by magwrap** [comment]
# Important
Update the UML diagram cause you added multiple new classes but didn't include them on the diagram.
It can be very confusing for other developers!!

**Review by magwrap — CHANGES_REQUESTED** [review]
Oh and now with FileController on dev, you'll have to implement it.
- I think IDataSource won't be necesarry now 
- We will have to talk about the change about the design pattern becaues in UML diagram CSVController does everyting (Serializer, Deserialize, Read, Write Data) but you implemented it as CSVController only does serialization stuff and CSV DataSource serves as a endpoint, I'm gonna do the same in JsonController but _please_ inform others and discuss first 

Sorry for dragging this PR for so long.

**Comment by pkyeager** [comment]
> # Important
> Update the UML diagram cause you added multiple new classes but didn't include them on the diagram. It can be very confusing for other developers!!

Thank you, will do. 

It gets me thinking, that other developers just have to read the documentation and use only SourceDataManager.cs, why would it confuse them? 

The goal of building something, which is solid, scalable and OO is to create also nice layers of abstraction so that another devs don't have to understand the implementation to be able to use the component. 
 
 I know, we have to understand it for the exam and etc. Just curious, how it'd be in RL.

**Comment by pkyeager** [comment]
@magwrap please re-review, test and merge if this PR is ready.

**Comment by magwrap** [comment]
Resolved conflicts

**Review by KonyakB — APPROVED** [review]
i think everything looks good

**Review by KonyakB — APPROVED** [review]
okay now that merge conflicts have been taken care of im rebasing it

**Pull request merged**
