### PR TITLE
SP2-161-rewrite-the-unit-testing-class-for-source-data-manager-cs

### PR DESCRIPTION
**Pull request by pkyeager**
The SourceDataManager unit tests have been refactored, replacing CsvController with a custom StubDataSource for improved isolation and control.

The FetchTimeSeriesDataAsync test method has been updated to utilize this StubDataSource for data preparation and verification. 

Associated documentation has also been updated to reflect these changes and provide more detailed explanations of the test methods and their structure.

### CODE REVIEW

**Review by rikkiSnaebjornsson — APPROVED** [review]

**Comment by pkyeager** [comment]
@magwrap should be quite ok now.

**Comment by magwrap** [comment]
so i merge it if everything is okay?

**Comment by pkyeager** [comment]
4-Augen-Prinzip pls

**Comment by magwrap** [comment]
> 4-Augen-Prinzip pls

Ich spreche deutch nicht, english bitte

**Pull request merged**
