### PR TITLE
SP2-117 - create unit test for HeatingGrid.cs

### PR DESCRIPTION
**Pull request by KonyakB**
what the title says

### CODE REVIEW

**Comment by KonyakB** [comment]
i have no idea why the publish-docs check fail again 😭

**Comment by pkyeager** [comment]
@KonyakB Have you checked this?

image

**Comment by KonyakB** [comment]
no, i only changed my own stuff and didnt look at sdm

**Comment by pkyeager** [comment]
@KonyakB Ok, it seems like the FS has changed a bit, it's just a minor reference error, I will take care of it.

**Pull request merged**
