### PR TITLE
Unit testing/SP2-93-create-unit-test-for-optimizer

### PR DESCRIPTION
**Pull request by pkyeager**
Lightweight, minimalistic, efficient. Like me.

### CODE REVIEW

**Comment by magwrap** [comment]
> Lightweight, minimalistic, efficient. Like me.



> Lightweight, minimalistic, efficient. Like me.

forgot about humble!

**Review by magwrap — COMMENTED** [review]
Looks good, I would wait for #84  to merge first bcs this branch has it commits.

I would maybe add more checks in first Unit Tests like more production units not just the first one, but it's not a requirement as it works as it is, just if you have some free time on your hands.

**Review by magwrap — APPROVED** [review]
lgtm

**Comment by pkyeager** [comment]
@KonyakB I need the newest OPT implementation and I wasn't sure if the unit testing branch is stable and updated enough. 

so I branched out from the most updated branch and didn't want somehow break unit testing branch with the newest branch state.

**Review by KonyakB — APPROVED** [review]
looks good, (i understand now why you wanted to merge into dev)

**Pull request merged**
