### PR TITLE
SP2-139-added Makefile to run either console app or web app easier

### PR DESCRIPTION
**Pull request by magwrap**
- added make file to run all the apis and web app with one command or just run console app easier
- added to the README.md steps how to use the Makefile

!!! PLEASE TEST ON YOUR MACHINE !!!
I've tried to include every type (meaning windows, macos and nixos) but it still may not work, try running the script on your machine and provide feedback.

### CODE REVIEW

**Comment by magwrap** [comment]
it doesn't run on windows out of the box (you need to install make for example via choco) but it still doesn't work after so idk

**Comment by frske** [comment]
Try rebooting

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by pkyeager** [comment]
@magwrap, as mentioned yesterday. I tested  using a custom shell script, which would run the 5 projects directly couple weeks ago. Less elegant, but would work. 

this could be run_projects.sh in root folder
`dotnet run --project ./projects/proj1/proj1.csproj`
`dotnet run --project ./projects/proj1/proj2.csproj`
`dotnet run --project ./projects/proj1/proj3.csproj`
`dotnet run --project ./projects/proj1/proj4.csproj`
`dotnet run --project ./projects/proj1/proj5.csproj`

then  - allow the script to be executed
`chmod +x run_projects.sh`
then
`./run_projects.sh`

I think I found it in some documentation a while ago, when I was building my own API-Solution for practice. 

PS: No guarantee

**Comment by magwrap** [comment]
> @magwrap, as mentioned yesterday. I tested using a custom shell script, which would run the 5 projects directly couple weeks ago. Less elegant, but would work.
> 
> this could be run_projects.sh in root folder `dotnet run --project ./projects/proj1/proj1.csproj` `dotnet run --project ./projects/proj1/proj2.csproj` `dotnet run --project ./projects/proj1/proj3.csproj` `dotnet run --project ./projects/proj1/proj4.csproj` `dotnet run --project ./projects/proj1/proj5.csproj`
> 
> then - allow the script to be executed `chmod +x run_projects.sh` then `./run_projects.sh`
> 
> I think I found it in some documentation a while ago, when I was building my own API-Solution for practice.
> 
> PS: No guarantee

gonna try it

**Review by rikkiSnaebjornsson — COMMENTED** [review]
Runs on Windows

**Comment by rikkiSnaebjornsson** [comment]
Works Again, nice work!

**Comment by pkyeager** [comment]
Will test this after I managed to finish blazor BTF implementation

**Comment by magwrap** [comment]
Gonna merge it into SP2-44 so I can work on the Optimizer API

**Pull request closed without merging**
