### PR TITLE
SP2-116 production unit unit tests

### PR DESCRIPTION
**Pull request by KonyakB**
- added unit tests for production unit class
- added documentation for the unit test

### CODE REVIEW

**Review by frske — APPROVED** [review]
Looks good to me. Nothing more can be added here

**Review by magwrap — CHANGES_REQUESTED** [review]
Move ProductionUnitTest.md to docs/ directory with coresponding structure.
E.g docs/Heatington.Tests/Models/ProductionUnitTests.md

 !!! remember to edit toc.yml file, it should be explained in Introduction.md file !!!

**Comment by KonyakB** [comment]
> Move ProductionUnitTest.md to docs/ directory with coresponding structure. E.g docs/Heatington.Tests/Models/ProductionUnitTests.md
> 
> !!! remember to edit toc.yml file, it should be explained in Introduction.md file !!!

yes we discuss this yesterday but since the issue branch SP2-111 still had the old filesystem i didnt really knew what to do

**Comment by magwrap** [comment]
@KonyakB have you pushed the changes cuz I can't see them here?

**Review by magwrap — APPROVED** [review]
lgtm

**Pull request merged**
