### PR TITLE
SP2-85-create read write controller and file controller

### PR DESCRIPTION
**Pull request by magwrap**
# Not tested 

**Creating pull request not to slow others down  by my slow pace. **
If you need this class for work, then merge, if not, wait for tests.

- Created IReadWriteController --> it's a interface for all classes performing read/write operations
- Created FileController --> it is supposed to be universal class for reading files BEFORE serializing them to csv, json, etc...
- Created Documentation directory, with documentation for FileController, it is mostly experimental, to try if we may want to use it or completely ignore it 
- Create static Utilities class with DisplayException method

### CODE REVIEW

**Review by pkyeager — COMMENTED** [review]
As always, nice code. 

Don't forget to change documentation style to external.

**Comment by magwrap** [comment]
I think it's finished.

- File Controller is now fully generic, only inside it works on strings, I'm not sure if that will be a problem. Maybe something can go bad when boxing and unboxing the generic data, but it should be an easy fix if it bothers anyone.
- created tests for FileController
- created new directory called "Documentation" mirroring the structure of a project but containing only markdown files with documentation
- changed name of the image storing the example of a grid

**Review by KonyakB — APPROVED** [review]
didn't really read all the documentation yet but the code seems very solid 🫡

(also genuine question, why is it better to have the operation status enums in a separate file)

**Comment by magwrap** [comment]
> didn't really read all the documentation yet but the code seems very solid 🫡
> 
> (also genuine question, why is it better to have the operation status enums in a separate file)

I think readability, you can clearly see where it is and that it exists so everyone can use it.

**Pull request merged**
